#Script generates flow parameters (a and b) for the cities generated by make_skeleton_cities.jl
using TrafficNetworks, SkeletonCities


cd("Data")
top_dir = pwd()
subdirs = readdir()

for dir in subdirs

    cd(dir)

    file_list = readdir()
    split_list = map(x -> split(x, '.'), file_list)
    indices = find(x -> x[end] == "json", split_list)
    file_list =  file_list[indices] #keep only JSON files

    counter = 0
    for file in file_list
        counter += 1 # Counts the file number we are on
        g = load_graph(file)

        a_params = Array{Float64,1}()
        b_params = Array{Float64,1}()

        for i in 1:num_edges(g)

            dist = norm(g.edges[i].target.pos - g.edges[i].source.pos)
            a = dist #this can be changed to introduce noise (should do...)
            b = rand()*0.4*a # This can also be changed...

            push!(a_params, a)
            push!(b_params, b)
        end

        graph_name = split(file_list[counter], ".json")[1]
        file_suffix = "_params.txt"
        header = "#Parameter file for graph $(graph_name) in this same dir\n#a\tb\n"

        data = hcat(a_params, b_params)

        f = open(graph_name*file_suffix, "w")
        write(f, header)
        writedlm(f, data)
        close(f)
    end
    cd(top_dir)
end
